name: BridgePractice
version: 1.0
main: me.alen_alex.bridgepractice.BridgePractice
authors: [ Alen_Alex ]
description: A plugin for practicing bridging
depend:
  - CoreAPI
softdepend:
  - PlaceholderAPI
commands:
  practiceadmin:
    description: "The adminstrative command for Bridgepractice."
    permission: "practice.admin"
  island:
    description: "Command for players"
  playerlist:
    aliases:
      - p
      - plist
      - players
    description: "A command for an interactice player list GUI"
  timer:
    description: "Player timer related commands!"

