name: BridgePractice
version: 1.0
main: me.alen_alex.bridgepractice.BridgePractice
authors: [ Alen_Alex ]
description: A plugin for practicing Bedwars Bridging!
depend:
  - CoreAPI
softdepend:
  - PlaceholderAPI
  - AdvancedReplay
  - Citizens
commands:
  practiceadmin:
    description: "The adminstrative command for Bridgepractice."
    permission: "practice.admin"
  island:
    description: "Command for players"
    aliases:
      - "is"
  playerlist:
    aliases:
      - p
      - plist
      - players
    description: "A command for an interactice player list GUI"
  timer:
    description: "Player timer related commands!"
  effect:
    description: "Player effect related commands"
    aliases:
      - "particleeffect"
      - "pe"
  firework:
    description: "Player Firework related commands"
  resetisland:
    description: "Command for resetting islands"
    permission: "practice.admin.reset"
  sessionreplay:
    aliases:
      - sr
      - sreplay
      - practicereplay
      - preplay
    description: "Command for opening replay menu"
  block:
    description: "A command for player to open up the material menu"
    aliases:
      - blocks

permissions:
  practice.gui.particle:
    default: true
  practice.timer:
    default: true
  practice.gui.replay:
    default: true
  practice.gui.block:
      default: true

